DROP TABLE IF EXISTS MONEDAS;
CREATE TABLE MONEDAS(
ID BIGINT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
SIMBOLO VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS MERCADOS;
CREATE TABLE MERCADOS(
ID BIGINT NOT NULL,
MONEDA BIGINT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(MONEDA) REFERENCES MONEDAS(ID)
);

DROP TABLE IF EXISTS VALORES;
CREATE TABLE VALORES(
ID BIGINT NOT NULL,
MONEDA BIGINT NOT NULL,
MERCADO BIGINT NOT NULL,
ACTIVO BOOLEAN NOT NULL,
COMPRA DECIMAL(14,4) NOT NULL,
VENTA DECIMAL(14,4) NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(MONEDA) REFERENCES MONEDAS(ID),
FOREIGN KEY(MERCADO) REFERENCES MERCADOS(ID)
);

INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO) VALUES(1,'Peso argentino','ARS$');
INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO) VALUES(2,'Dolar estadounidense','US$');

INSERT INTO MERCADOS(ID,MONEDA,NOMBRE) VALUES(1,1,'Mercado de cambio argentino');

INSERT INTO VALORES(ID,MONEDA,MERCADO,ACTIVO,COMPRA,VENTA,FECHA) VALUES(1,2,1,FALSE,365,370,'2023-1-1');
INSERT INTO VALORES(ID,MONEDA,MERCADO,ACTIVO,COMPRA,VENTA,FECHA) VALUES(2,2,1,TRUE,375,380,'2023-2-1');