DROP TABLE IF EXISTS MONEDAS;
CREATE TABLE IF NOT EXISTS MONEDAS(
	ID BIGINT  not null,
	NOMBRE VARCHAR(25) not null,
	SIMBOLO VARCHAR(25) not null,
	COMPRA DECIMAL(14,4) not null,
	VENTA DECIMAL(14,4) not null,
	VARIACION DECIMAL(14,4) not null,
	PRIMARY KEY(ID)
);

INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO,COMPRA,VENTA,VARIACION) VALUES(1,'Peso argentino','ARS$',1,1,0);
INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO,COMPRA,VENTA,VARIACION) VALUES(2,'Dolar estadounidense','US$',375,380,0.59);