DROP TABLE IF EXISTS MONEDAS;
CREATE TABLE MONEDAS(
ID BIGINT NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
SIMBOLO VARCHAR(25) NOT NULL,
PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS VALORES;
CREATE TABLE VALORES(
ID BIGINT NOT NULL,
MONEDA BIGINT NOT NULL,
ACTIVO BOOLEAN NOT NULL,
COMPRA DECIMAL(14,4) NOT NULL,
VENTA DECIMAL(14,4) NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(MONEDA) REFERENCES MONEDAS(ID)
);

INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO) VALUES(1,'Peso argentino','ARS$');
INSERT INTO MONEDAS(ID,NOMBRE,SIMBOLO) VALUES(2,'Dolar estadounidense','US$');

INSERT INTO VALORES(ID,MONEDA,ACTIVO,COMPRA,VENTA,FECHA) VALUES(1,1,TRUE,1,1,'2023-1-1');
INSERT INTO VALORES(ID,MONEDA,ACTIVO,COMPRA,VENTA,FECHA) VALUES(2,2,FALSE,365,370,'2023-1-1');
INSERT INTO VALORES(ID,MONEDA,ACTIVO,COMPRA,VENTA,FECHA) VALUES(3,2,TRUE,375,380,'2023-2-1');